[project]
name = "dcat-us-3"
version = "0.1.0"
description = ""
authors = [
    {name = "Datagov Team",email = "datagovhelp@gsa.gov"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "jsonschema[format] (>=4.26.0,<5.0.0)",
    "json-schema-for-humans (>=1.5.1,<2.0.0)",
    "click (>=8.3.1,<9.0.0)",
    "beautifulsoup4 (>=4.12.0,<5.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
pytest-cov = "^6.0.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
python_files = ["test_*.py"]
addopts = [
    "-ra",
    "--strict-markers",
    "--strict-config",
    "--ignore=test_json_schema.py",
]
